version: 2.1

orbs:
  linter: thekevjames/linter@0.1

jobs:
  pypi:
    docker:
      - image: python:3.7.4-slim
    steps:
      - run: pip install pyopenssl twine
      - checkout
      - deploy:
          name: upload to pypi
          command: |
            # TODO: Simplify when everything is split into modules
            # The check for the dash in the tag name won't be necessary
            if [[ $CIRCLE_TAG =~ "-" ]]
            then
              export PROJECT=$(echo "${CIRCLE_TAG}" | sed 's/-.*//')
              cd "${PROJECT}"
            fi
            python setup.py sdist bdist_wheel
            twine upload dist/*

  github:
    docker:
      - image: python:3.7.4-alpine
    steps:
      - run: apk add --no-cache curl git openssh-client
      - checkout
      - run:
          name: install github-release
          command: |
            curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 > github-release.tar.bz2
            tar xjf github-release.tar.bz2
            rm -f github-release.tar.bz2
      - deploy:
          name: create GitHub release
          command: |
            # TODO: Simplify when everything is split into modules
            # The check for the dash in the tag name won't be necessary
            if [[ $CIRCLE_TAG =~ "-" ]]
            then
              export PROJECT=$(echo "${CIRCLE_TAG}" | sed 's/-.*//')
              export PREV_RELEASE=$(git tag --sort=version:refname | grep ${PROJECT} | tail -n2 | head -n1)
              [ "${PREV_RELEASE}" = "${CIRCLE_TAG}" ] && export PREV_RELEASE=$(git rev-list --max-parents=0 HEAD)
              [ -z "${PREV_RELEASE}" ] && export PREV_RELEASE=$(git rev-list --max-parents=0 HEAD)

              git log ${PREV_RELEASE}..${CIRCLE_TAG} --pretty=format:'- %s' > release-description.md
              ./bin/linux/amd64/github-release release -t "${CIRCLE_TAG}"
              cat release-description.md | grep ${PROJECT} | ./bin/linux/amd64/github-release edit -t ${CIRCLE_TAG} -d -
            else
              export PREV_RELEASE=$(git tag --sort=version:refname | tail -n2 | head -n1)
              [ "${PREV_RELEASE}" = "${CIRCLE_TAG}" ] && export PREV_RELEASE=$(git rev-list --max-parents=0 HEAD)
              [ -z "${PREV_RELEASE}" ] && export PREV_RELEASE=$(git rev-list --max-parents=0 HEAD)

              git log ${PREV_RELEASE}..${CIRCLE_TAG} --pretty=format:'- %s' > release-description.md
              ./bin/linux/amd64/github-release release -t "${CIRCLE_TAG}"
              cat release-description.md | ./bin/linux/amd64/github-release edit -t ${CIRCLE_TAG} -d -
            fi

workflows:
  run-jobs:
    jobs:
      - pypi:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              # TODO make project name mandatory when split into modules
              only: /([a-z]+-)?[0-9]+\.[0-9]+\.[0-9]+/
      - github:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              # TODO make project name mandatory when split into modules
              only: /([a-z]+-)?[0-9]+\.[0-9]+\.[0-9]+/
